/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Gitbbon. All rights reserved.
 *  Licensed under the MIT License.
 *--------------------------------------------------------------------------------------------*/

import * as vscode from 'vscode';
import { ProjectManager } from './projectManager';
import { GitGraphViewProvider } from './gitGraphViewProvider';
import { GitHubSyncManager } from './githubSyncManager';

/**
 * Extension activation
 */
export async function activate(context: vscode.ExtensionContext): Promise<void> {
	console.log('Gitbbon Manager extension activating...');
	const projectManager = new ProjectManager();
	const githubSyncManager = new GitHubSyncManager(projectManager);

	// Register Git Graph View Provider
	const gitGraphProvider = new GitGraphViewProvider(context.extensionUri);
	context.subscriptions.push(
		vscode.window.registerWebviewViewProvider(GitGraphViewProvider.viewType, gitGraphProvider)
	);

	// Register initialize command (manual trigger)
	const initializeCommand = vscode.commands.registerCommand(
		'gitbbon.manager.initialize',
		async () => {
			await projectManager.startup();
		}
	);
	context.subscriptions.push(initializeCommand);

	// Register Sync Command
	const syncCommand = vscode.commands.registerCommand(
		'gitbbon.manager.sync',
		async () => {
			await githubSyncManager.sync(false); // Interactive mode
			await gitGraphProvider.refresh();
		}
	);
	context.subscriptions.push(syncCommand);

	// Status Bar Item for Sync
	const syncStatusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left, 100);
	syncStatusBarItem.text = `$(sync) Sync`;
	syncStatusBarItem.command = 'gitbbon.manager.sync';
	syncStatusBarItem.tooltip = 'GitHub와 동기화';
	syncStatusBarItem.show();
	context.subscriptions.push(syncStatusBarItem);

	// Register autoCommit command
	const autoCommitCommand = vscode.commands.registerCommand(
		'gitbbon.manager.autoCommit',
		async () => {
			const result = await projectManager.autoCommit();
			console.log('Auto Commit Result:', result);
			if (result.success) {
				await gitGraphProvider.refresh();
			}
			return result;
		}
	);
	context.subscriptions.push(autoCommitCommand);

	// Register reallyFinal command
	const reallyFinalCommand = vscode.commands.registerCommand(
		'gitbbon.manager.reallyFinal',
		async () => {
			const result = await projectManager.reallyFinalCommit();
			console.log('Really Final Result:', result);
			if (result.success) {
				await gitGraphProvider.refresh();
				// Trigger Sync after really final commit (Silent mode)
				console.log('[Extension] Triggering Sync after Really Final Commit (Silent)...');
				githubSyncManager.sync(true)
					.then(() => {
						console.log('[Extension] Post-commit sync completed, refreshing git graph...');
						return gitGraphProvider.refresh();
					})
					.catch(e => console.error('Post-commit sync failed:', e));
			}
			return result;
		}
	);
	context.subscriptions.push(reallyFinalCommand);

	// 30-minute Periodic Sync (Silent mode)
	const syncInterval = setInterval(() => {
		console.log('[Extension] Triggering periodic sync (30m, Silent)...');
		githubSyncManager.sync(true)
			.then(() => {
				console.log('[Extension] Periodic sync completed, refreshing git graph...');
				return gitGraphProvider.refresh();
			})
			.catch(e => console.error('Periodic sync failed:', e));
	}, 30 * 60 * 1000); // 30 minutes
	context.subscriptions.push({ dispose: () => clearInterval(syncInterval) });


	// Startup logic
	// We run this slightly deferred to let VS Code settle, though 'activate' is already part of startup.
	// We don't want to block extension activation too long, so we run async.
	projectManager.startup().then(async () => {
		// Focus Git Graph View on startup
		// The command 'gitbbon.gitGraph.focus' is automatically generated by VS Code for the view with ID 'gitbbon.gitGraph'.
		await vscode.commands.executeCommand('gitbbon.gitGraph.focus').then(undefined, err => {
			console.warn('[Extension] Could not focus Git Graph view:', err);
		});

		// Attempt initial sync in SILENT mode.
		// If user never authenticated, this will do nothing.
		console.log('[Extension] Triggering startup sync (Silent)...');
		githubSyncManager.sync(true)
			.then(() => {
				console.log('[Extension] Startup sync completed, refreshing git graph...');
				return gitGraphProvider.refresh();
			})
			.catch(e => console.error('Startup sync failed:', e));
	}).catch(err => {
		console.error('Startup failed:', err);
	});

	// Restore File Command
	const restoreFileCommand = vscode.commands.registerCommand('gitbbon.restoreFile', async (commitHash: string, fileUri: vscode.Uri) => {
		const workspaceFolder = vscode.workspace.getWorkspaceFolder(fileUri);
		if (!workspaceFolder) {
			vscode.window.showErrorMessage('워크스페이스를 찾을 수 없습니다.');
			return;
		}

		try {
			const relativePath = vscode.workspace.asRelativePath(fileUri);

			const confirm = await vscode.window.showWarningMessage(
				`'${relativePath}' 파일을 ${commitHash.substring(0, 7)} 버전으로 복구하시겠습니까? (현재 변경사항은 덮어쓰여집니다)`,
				'복구',
				'취소'
			);

			if (confirm !== '복구') {
				return;
			}

			// git checkout {commitHash} -- {relativePath}
			const { exec } = require('child_process');
			const command = `git checkout ${commitHash} -- "${relativePath}"`;

			await new Promise((resolve, reject) => {
				exec(command, { cwd: workspaceFolder.uri.fsPath }, (error: any, stdout: any, stderr: any) => {
					if (error) {
						reject(error);
						return;
					}
					resolve(stdout);
				});
			});

			vscode.window.showInformationMessage(`${relativePath} 파일이 복구되었습니다.`);
		} catch (error) {
			console.error('File restore failed:', error);
			vscode.window.showErrorMessage(`파일 복구 실패: ${error}`);
		}
	});
	context.subscriptions.push(restoreFileCommand);

	// Comparison Mode Switch Command

	// 현재 커밋 컨텍스트를 저장 (모드 변경 간 유지)
	let currentCommitContext: { historyItemId: string; rootUri: vscode.Uri } | undefined;

	const switchComparisonModeCommand = vscode.commands.registerCommand(
		'gitbbon.switchComparisonMode',
		async (args: { mode: string; multiDiffSource: string }) => {
			console.log('Switch Comparison Mode triggered:', args);
			if (!args.multiDiffSource) {
				vscode.window.showErrorMessage('No Multi Diff Source provided.');
				return;
			}

			try {
				const uri = vscode.Uri.parse(args.multiDiffSource);
				console.log('uri.scheme:', uri.scheme);

				// scm-history-item 스킴인 경우 컨텍스트 갱신
				if (uri.scheme === 'scm-history-item') {
					const query = JSON.parse(uri.query);
					const { historyItemId } = query;
					const rootUri = vscode.workspace.workspaceFolders?.[0]?.uri;
					if (historyItemId && rootUri) {
						currentCommitContext = { historyItemId, rootUri };
						console.log('Updated commit context:', currentCommitContext);
					}
				}

				// 저장된 컨텍스트가 없으면 에러
				if (!currentCommitContext) {
					vscode.window.showWarningMessage('비교 모드 변경은 Git Graph에서 커밋을 다시 선택해 주세요.');
					return;
				}

				const { historyItemId, rootUri } = currentCommitContext;

				// Get current branch name dynamically
				const getCurrentBranch = (): Promise<string> => {
					return new Promise((resolve, reject) => {
						const cp = require('child_process');
						cp.exec('git rev-parse --abbrev-ref HEAD', { cwd: rootUri.fsPath }, (err: Error | null, stdout: string) => {
							if (err) {
								reject(err);
								return;
							}
							resolve(stdout.trim());
						});
					});
				};

				// Resolve branch/ref name to commit hash
				const resolveRefToCommitHash = (ref: string): Promise<string> => {
					return new Promise((resolve, reject) => {
						const cp = require('child_process');
						cp.exec(`git rev-parse ${ref}`, { cwd: rootUri.fsPath }, (err: Error | null, stdout: string) => {
							if (err) {
								reject(err);
								return;
							}
							resolve(stdout.trim());
						});
					});
				};

				let parentCommitId: string | undefined = undefined;


				console.log("🚀 ~ activate ~ args.mode:", args.mode)
				switch (args.mode) {
					case 'savepoint':
						// 현재 브랜치의 마지막 버전(커밋 해시)과 비교
						try {
							const currentBranch = await getCurrentBranch();
							const commitHash = await resolveRefToCommitHash(currentBranch);
							parentCommitId = commitHash;
							console.log(`Savepoint mode: comparing with '${currentBranch}' -> commit ${commitHash}`);
						} catch (e) {
							console.error('Failed to resolve branch to commit:', e);
						}
						break;
					case 'draft':
						// auto-save/현재브랜치의 커밋 해시와 비교
						try {
							const currentBranch = await getCurrentBranch();
							const autoSaveBranch = `auto-save/${currentBranch}`;
							const commitHash = await resolveRefToCommitHash(autoSaveBranch);
							parentCommitId = commitHash;
							console.log(`Draft mode: comparing with '${autoSaveBranch}' -> commit ${commitHash}`);
						} catch (e) {
							console.error('Failed to resolve auto-save branch to commit:', e);
							vscode.window.showWarningMessage(`auto-save 브랜치를 찾을 수 없습니다.`);
						}
						break;
					case 'default':
						// 이전 버전(커밋의 실제 부모)과 비교
						try {
							const commitParent = await resolveRefToCommitHash(`${historyItemId}^`);
							parentCommitId = commitParent;
							console.log(`Default mode: comparing with parent commit ${commitParent}`);
						} catch (e) {
							console.error('Failed to resolve parent commit:', e);
							vscode.window.showWarningMessage('부모 커밋을 찾을 수 없습니다.');
						}
						break;
				}

				console.log(`Switching mode to ${args.mode}, parent: ${parentCommitId}`);

				if (!parentCommitId) {
					// Default 모드: 기존 Core 명령어 사용
					await vscode.commands.executeCommand(
						'gitbbon.openCommitInMultiDiffEditor',
						rootUri,
						historyItemId,
						undefined
					);
				} else {
					// Custom 비교: git diff를 직접 실행하여 파일 목록 가져오기
					const getChangedFiles = (): Promise<{ status: string, file: string, originalFile?: string }[]> => {
						return new Promise((resolve, reject) => {
							const cp = require('child_process');
							cp.exec(
								`git diff --name-status ${parentCommitId}..${historyItemId}`,
								{ cwd: rootUri.fsPath },
								(err: Error | null, stdout: string) => {
									if (err) {
										reject(err);
										return;
									}
									const files = stdout.trim().split('\n').filter(l => l).map(line => {
										const parts = line.split('\t');
										const status = parts[0];
										if (status.startsWith('R')) {
											// Renamed: R100\toldname\tnewname
											return { status: 'R', file: parts[2], originalFile: parts[1] };
										}
										return { status, file: parts[1] };
									});
									resolve(files);
								}
							);
						});
					};

					try {
						const changedFiles = await getChangedFiles();
						console.log(`[switchComparisonMode] Changed files:`, changedFiles);

						if (changedFiles.length === 0) {
							vscode.window.showInformationMessage('변경된 파일이 없습니다.');
							return;
						}

						// git: 스킴 URI 생성 헬퍼
						const toGitUri = (filePath: string, ref: string): vscode.Uri => {
							const fileUri = vscode.Uri.file(`${rootUri.fsPath}/${filePath}`);
							const params = { path: fileUri.fsPath, ref };
							return fileUri.with({
								scheme: 'git',
								query: JSON.stringify(params)
							});
						};

						// MultiDiffEditorInput resources 구성
						// default 모드: 부모(parentCommitId)가 왼쪽, 현재(historyItemId)가 오른쪽 (일반적인 diff)
						// savepoint/draft 모드: 현재(historyItemId)가 왼쪽, Save Point/auto-save가 오른쪽
						const shouldSwap = args.mode === 'savepoint' || args.mode === 'draft';

						const resources = changedFiles.map(change => {
							let originalUri: vscode.Uri | undefined;
							let modifiedUri: vscode.Uri | undefined;

							// 왼쪽 = original, 오른쪽 = modified
							const leftRef = shouldSwap ? historyItemId : parentCommitId!;
							const rightRef = shouldSwap ? parentCommitId! : historyItemId;

							switch (change.status) {
								case 'A': // Added
									if (shouldSwap) {
										originalUri = toGitUri(change.file, historyItemId);
									} else {
										modifiedUri = toGitUri(change.file, historyItemId);
									}
									break;
								case 'D': // Deleted
									if (shouldSwap) {
										modifiedUri = toGitUri(change.file, parentCommitId!);
									} else {
										originalUri = toGitUri(change.file, parentCommitId!);
									}
									break;
								case 'R': // Renamed
									originalUri = toGitUri(shouldSwap ? change.file : change.originalFile!, leftRef);
									modifiedUri = toGitUri(shouldSwap ? change.originalFile! : change.file, rightRef);
									break;
								default: // Modified
									originalUri = toGitUri(change.file, leftRef);
									modifiedUri = toGitUri(change.file, rightRef);
									break;
							}

							return { originalUri, modifiedUri };
						});

						// Multi Diff Editor 열기
						const label = `${historyItemId.substring(0, 8)} vs ${parentCommitId.substring(0, 8)}`;
						await vscode.commands.executeCommand('_workbench.openMultiDiffEditor', {
							title: label,
							resources
						});

					} catch (e) {
						console.error('[switchComparisonMode] Failed to get changed files:', e);
						vscode.window.showErrorMessage('변경된 파일 목록을 가져오지 못했습니다.');
					}
				}

			} catch (e) {
				console.error('Failed to switch comparison mode:', e);
				vscode.window.showErrorMessage('Failed to switch comparison mode.');
			}
		}
	);
	context.subscriptions.push(switchComparisonModeCommand);

	// Restore to Version Command
	const restoreToVersionCommand = vscode.commands.registerCommand(
		'gitbbon.restoreToVersion',
		async (args: { commitHash: string; multiDiffSource: string }) => {
			console.log('Restore to Version triggered:', args);

			if (!args.commitHash) {
				vscode.window.showErrorMessage('No commit hash provided for restoration.');
				return;
			}

			// 1. Resolve Root URI
			let rootUri: vscode.Uri | undefined;
			if (args.multiDiffSource) {
				try {
					const uri = vscode.Uri.parse(args.multiDiffSource);
					if (uri.scheme === 'scm-history-item') {
						rootUri = vscode.workspace.workspaceFolders?.[0]?.uri; // fallback to first folder usually works
					}
				} catch (e) {
					console.error('Failed to parse multiDiffSource:', e);
				}
			}
			if (!rootUri) {
				rootUri = vscode.workspace.workspaceFolders?.[0]?.uri;
			}
			if (!rootUri) {
				vscode.window.showErrorMessage('No workspace folder found.');
				return;
			}

			const cwd = rootUri.fsPath;
			const targetCommitHash = args.commitHash;

			// Confirm with user
			const confirm = await vscode.window.showWarningMessage(
				`현재 상태를 커밋 '${targetCommitHash.substring(0, 7)}' 상태로 복원하시겠습니까? (현재 내용은 자동으로 백업됩니다)`,
				{ modal: true },
				'복원하기'
			);
			if (confirm !== '복원하기') {
				return;
			}

			try {
				await vscode.window.withProgress({
					location: vscode.ProgressLocation.Notification,
					title: "버전 복원 중...",
					cancellable: false
				}, async (progress) => {

					// Step 1: Safety Check & Backup (Really Final)
					progress.report({ message: "현재 작업 내용 백업 중..." });
					// Check for uncommitted changes
					const hasChanges = await new Promise<boolean>((resolve) => {
						const cp = require('child_process');
						cp.exec('git status --porcelain', { cwd }, (err: Error | null, stdout: string) => {
							resolve(!!(stdout && stdout.trim().length > 0));
						});
					});

					if (hasChanges) {
						console.log('[Restore] Changes detected, triggering Really Final...');
						const backupResult = await projectManager.reallyFinalCommit();
						if (!backupResult.success) {
							throw new Error(`Backup failed: ${backupResult.message}`);
						}
					} else {
						console.log('[Restore] Clean state, skipping backup.');
					}

					// Step 2: Get Target Commit Title
					progress.report({ message: "타겟 커밋 정보 조회 중..." });
					const targetTitle = await new Promise<string>((resolve, reject) => {
						const cp = require('child_process');
						cp.exec(`git log -1 --pretty=%s ${targetCommitHash}`, { cwd }, (err: Error | null, stdout: string) => {
							if (err) {
								reject(err);
							} else {
								resolve(stdout.trim());
							}
						});
					});

					// Step 3: Read Tree (Restore Content)
					progress.report({ message: "과거 상태 불러오는 중..." });
					await new Promise<void>((resolve, reject) => {
						const cp = require('child_process');
						// -u: updates the index and checking out files
						// --reset: performs a merge rather than a hard overwrite if possible, but here we want to match target
						// Actually 'git read-tree -u --reset <tree-ish>' matches the index and worktree to the tree-ish.
						cp.exec(`git read-tree -u --reset ${targetCommitHash}`, { cwd }, (err: Error | null, stderr: string) => {
							if (err) {
								console.error('git read-tree failed:', stderr);
								reject(err);
							} else {
								resolve();
							}
						});
					});

					// Step 4: Create Restore Commit
					progress.report({ message: "복원 커밋 생성 중..." });
					const restoreMessage = `복원 : ${targetTitle} (${targetCommitHash.substring(0, 7)})`;
					await new Promise<void>((resolve, reject) => {
						const cp = require('child_process');
						cp.exec(`git commit -m "${restoreMessage}"`, { cwd }, (err: Error | null, stderr: string) => {
							if (err) {
								reject(err);
							} else {
								resolve();
							}
						});
					});

					// Step 5: Sync
					progress.report({ message: "원격 저장소 동기화 중..." });
					await githubSyncManager.sync(false);

					// Refresh Git Graph
					await gitGraphProvider.refresh();

					vscode.window.showInformationMessage(`성공적으로 복원되었습니다: ${restoreMessage}`);
				});
			} catch (e) {
				console.error('[Restore] Failed:', e);
				vscode.window.showErrorMessage(`복원 실패: ${e}`);
			}
		}
	);
	context.subscriptions.push(restoreToVersionCommand);

	console.log('Gitbbon Manager extension activated!');
}

/**
 * Extension deactivation
 */
export function deactivate(): void {
	console.log('Gitbbon Manager extension deactivated');
}
