/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Gitbbon. All rights reserved.
 *  Licensed under the MIT License.
 *--------------------------------------------------------------------------------------------*/

import * as vscode from 'vscode';
import { ProjectManager } from './projectManager';
import { GitGraphViewProvider } from './gitGraphViewProvider';
import { GitHubSyncManager } from './githubSyncManager';

/**
 * Extension activation
 */
export async function activate(context: vscode.ExtensionContext): Promise<void> {
	console.log('Gitbbon Manager extension activating...');
	const projectManager = new ProjectManager();
	const githubSyncManager = new GitHubSyncManager(projectManager);

	// Register Git Graph View Provider
	const gitGraphProvider = new GitGraphViewProvider(context.extensionUri);
	context.subscriptions.push(
		vscode.window.registerWebviewViewProvider(GitGraphViewProvider.viewType, gitGraphProvider)
	);

	// Register initialize command (manual trigger)
	const initializeCommand = vscode.commands.registerCommand(
		'gitbbon.manager.initialize',
		async () => {
			await projectManager.startup();
		}
	);
	context.subscriptions.push(initializeCommand);

	// Register Sync Command
	const syncCommand = vscode.commands.registerCommand(
		'gitbbon.manager.sync',
		async () => {
			await githubSyncManager.sync(false); // Interactive mode
			await gitGraphProvider.refresh();
		}
	);
	context.subscriptions.push(syncCommand);

	// Status Bar Item for Sync
	const syncStatusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left, 100);
	syncStatusBarItem.text = `$(sync) Sync`;
	syncStatusBarItem.command = 'gitbbon.manager.sync';
	syncStatusBarItem.tooltip = 'GitHub와 동기화';
	syncStatusBarItem.show();
	context.subscriptions.push(syncStatusBarItem);

	// Register autoCommit command
	const autoCommitCommand = vscode.commands.registerCommand(
		'gitbbon.manager.autoCommit',
		async () => {
			const result = await projectManager.autoCommit();
			console.log('Auto Commit Result:', result);
			if (result.success) {
				await gitGraphProvider.refresh();
			}
			return result;
		}
	);
	context.subscriptions.push(autoCommitCommand);

	// Register reallyFinal command
	const reallyFinalCommand = vscode.commands.registerCommand(
		'gitbbon.manager.reallyFinal',
		async () => {
			const result = await projectManager.reallyFinalCommit();
			console.log('Really Final Result:', result);
			if (result.success) {
				await gitGraphProvider.refresh();
				// Trigger Sync after really final commit (Silent mode)
				console.log('[Extension] Triggering Sync after Really Final Commit (Silent)...');
				githubSyncManager.sync(true)
					.then(() => {
						console.log('[Extension] Post-commit sync completed, refreshing git graph...');
						return gitGraphProvider.refresh();
					})
					.catch(e => console.error('Post-commit sync failed:', e));
			}
			return result;
		}
	);
	context.subscriptions.push(reallyFinalCommand);

	// 30-minute Periodic Sync (Silent mode)
	const syncInterval = setInterval(() => {
		console.log('[Extension] Triggering periodic sync (30m, Silent)...');
		githubSyncManager.sync(true)
			.then(() => {
				console.log('[Extension] Periodic sync completed, refreshing git graph...');
				return gitGraphProvider.refresh();
			})
			.catch(e => console.error('Periodic sync failed:', e));
	}, 30 * 60 * 1000); // 30 minutes
	context.subscriptions.push({ dispose: () => clearInterval(syncInterval) });


	// Startup logic
	// We run this slightly deferred to let VS Code settle, though 'activate' is already part of startup.
	// We don't want to block extension activation too long, so we run async.
	projectManager.startup().then(async () => {
		// Focus Git Graph View on startup
		// The command 'gitbbon.gitGraph.focus' is automatically generated by VS Code for the view with ID 'gitbbon.gitGraph'.
		await vscode.commands.executeCommand('gitbbon.gitGraph.focus').then(undefined, err => {
			console.warn('[Extension] Could not focus Git Graph view:', err);
		});

		// Attempt initial sync in SILENT mode.
		// If user never authenticated, this will do nothing.
		console.log('[Extension] Triggering startup sync (Silent)...');
		githubSyncManager.sync(true)
			.then(() => {
				console.log('[Extension] Startup sync completed, refreshing git graph...');
				return gitGraphProvider.refresh();
			})
			.catch(e => console.error('Startup sync failed:', e));
	}).catch(err => {
		console.error('Startup failed:', err);
	});

	// Comparison Mode Switch Command
	// 현재 커밋 컨텍스트를 저장 (모드 변경 간 유지)
	let currentCommitContext: { historyItemId: string; rootUri: vscode.Uri } | undefined;

	const switchComparisonModeCommand = vscode.commands.registerCommand(
		'gitbbon.switchComparisonMode',
		async (args: { mode: string; multiDiffSource: string }) => {
			console.log('Switch Comparison Mode triggered:', args);
			if (!args.multiDiffSource) {
				vscode.window.showErrorMessage('No Multi Diff Source provided.');
				return;
			}

			try {
				const uri = vscode.Uri.parse(args.multiDiffSource);
				console.log('uri.scheme:', uri.scheme);

				// scm-history-item 스킴인 경우 컨텍스트 갱신
				if (uri.scheme === 'scm-history-item') {
					const query = JSON.parse(uri.query);
					const { historyItemId } = query;
					const rootUri = vscode.workspace.workspaceFolders?.[0]?.uri;
					if (historyItemId && rootUri) {
						currentCommitContext = { historyItemId, rootUri };
						console.log('Updated commit context:', currentCommitContext);
					}
				}

				// 저장된 컨텍스트가 없으면 에러
				if (!currentCommitContext) {
					vscode.window.showWarningMessage('비교 모드 변경은 Git Graph에서 커밋을 다시 선택해 주세요.');
					return;
				}

				const { historyItemId, rootUri } = currentCommitContext;

				// Get current branch name dynamically
				const getCurrentBranch = (): Promise<string> => {
					return new Promise((resolve, reject) => {
						const cp = require('child_process');
						cp.exec('git rev-parse --abbrev-ref HEAD', { cwd: rootUri.fsPath }, (err: Error | null, stdout: string) => {
							if (err) {
								reject(err);
								return;
							}
							resolve(stdout.trim());
						});
					});
				};

				// Resolve branch/ref name to commit hash
				const resolveRefToCommitHash = (ref: string): Promise<string> => {
					return new Promise((resolve, reject) => {
						const cp = require('child_process');
						cp.exec(`git rev-parse ${ref}`, { cwd: rootUri.fsPath }, (err: Error | null, stdout: string) => {
							if (err) {
								reject(err);
								return;
							}
							resolve(stdout.trim());
						});
					});
				};

				let parentCommitId: string | undefined = undefined;


				console.log("🚀 ~ activate ~ args.mode:", args.mode)
				switch (args.mode) {
					case 'savepoint':
						// 현재 브랜치의 마지막 버전(커밋 해시)과 비교
						try {
							const currentBranch = await getCurrentBranch();
							const commitHash = await resolveRefToCommitHash(currentBranch);
							parentCommitId = commitHash;
							console.log(`Savepoint mode: comparing with '${currentBranch}' -> commit ${commitHash}`);
						} catch (e) {
							console.error('Failed to resolve branch to commit:', e);
						}
						break;
					case 'draft':
						// auto-save/현재브랜치의 커밋 해시와 비교
						try {
							const currentBranch = await getCurrentBranch();
							const autoSaveBranch = `auto-save/${currentBranch}`;
							const commitHash = await resolveRefToCommitHash(autoSaveBranch);
							parentCommitId = commitHash;
							console.log(`Draft mode: comparing with '${autoSaveBranch}' -> commit ${commitHash}`);
						} catch (e) {
							console.error('Failed to resolve auto-save branch to commit:', e);
							vscode.window.showWarningMessage(`auto-save 브랜치를 찾을 수 없습니다.`);
						}
						break;
					case 'default':
						parentCommitId = undefined; // Default behavior (compare with parent)
						break;
				}

				console.log(`Switching mode to ${args.mode}, parent: ${parentCommitId}`);

				if (!parentCommitId) {
					// Default 모드: 기존 Core 명령어 사용
					await vscode.commands.executeCommand(
						'gitbbon.openCommitInMultiDiffEditor',
						rootUri,
						historyItemId,
						undefined
					);
				} else {
					// Custom 비교: git diff를 직접 실행하여 파일 목록 가져오기
					const getChangedFiles = (): Promise<{ status: string, file: string, originalFile?: string }[]> => {
						return new Promise((resolve, reject) => {
							const cp = require('child_process');
							cp.exec(
								`git diff --name-status ${parentCommitId}..${historyItemId}`,
								{ cwd: rootUri.fsPath },
								(err: Error | null, stdout: string) => {
									if (err) {
										reject(err);
										return;
									}
									const files = stdout.trim().split('\n').filter(l => l).map(line => {
										const parts = line.split('\t');
										const status = parts[0];
										if (status.startsWith('R')) {
											// Renamed: R100\toldname\tnewname
											return { status: 'R', file: parts[2], originalFile: parts[1] };
										}
										return { status, file: parts[1] };
									});
									resolve(files);
								}
							);
						});
					};

					try {
						const changedFiles = await getChangedFiles();
						console.log(`[switchComparisonMode] Changed files:`, changedFiles);

						if (changedFiles.length === 0) {
							vscode.window.showInformationMessage('변경된 파일이 없습니다.');
							return;
						}

						// git: 스킴 URI 생성 헬퍼
						const toGitUri = (filePath: string, ref: string): vscode.Uri => {
							const fileUri = vscode.Uri.file(`${rootUri.fsPath}/${filePath}`);
							const params = { path: fileUri.fsPath, ref };
							return fileUri.with({
								scheme: 'git',
								query: JSON.stringify(params)
							});
						};

						// MultiDiffEditorInput resources 구성
						// savepoint/draft 모드: parentCommitId가 이전 버전이므로 왼쪽에 표시
						// 따라서 originalUri = parentCommitId, modifiedUri = historyItemId
						// 하지만 사용자가 원하는 것: Save Point/auto-save(이전)가 왼쪽
						// 현재 커밋(historyItemId)이 왼쪽, Save Point(parentCommitId)가 오른쪽이 되어야 함
						const resources = changedFiles.map(change => {
							let originalUri: vscode.Uri | undefined;
							let modifiedUri: vscode.Uri | undefined;

							// savepoint/draft: 현재 커밋(historyItemId)이 왼쪽, Save Point/auto-save가 오른쪽
							switch (change.status) {
								case 'A': // Added (현재 커밋에서 추가됨 → 이 경우 스왑하면 삭제된 것처럼 보임)
									// 스왑: 왼쪽=historyItemId(없음), 오른쪽=parentCommitId(있음) → Deleted처럼 표시
									originalUri = toGitUri(change.file, historyItemId);
									break;
								case 'D': // Deleted (현재 커밋에서 삭제됨)
									// 스왑: 왼쪽=historyItemId(있음), 오른쪽=parentCommitId(없음) → Added처럼 표시
									modifiedUri = toGitUri(change.file, parentCommitId!);
									break;
								case 'R': // Renamed
									originalUri = toGitUri(change.file, historyItemId);
									modifiedUri = toGitUri(change.originalFile!, parentCommitId!);
									break;
								default: // Modified
									originalUri = toGitUri(change.file, historyItemId);
									modifiedUri = toGitUri(change.file, parentCommitId!);
									break;
							}

							return { originalUri, modifiedUri };
						});

						// Multi Diff Editor 열기
						const label = `${historyItemId.substring(0, 8)} vs ${parentCommitId.substring(0, 8)}`;
						await vscode.commands.executeCommand('_workbench.openMultiDiffEditor', {
							title: label,
							resources
						});

					} catch (e) {
						console.error('[switchComparisonMode] Failed to get changed files:', e);
						vscode.window.showErrorMessage('변경된 파일 목록을 가져오지 못했습니다.');
					}
				}

			} catch (e) {
				console.error('Failed to switch comparison mode:', e);
				vscode.window.showErrorMessage('Failed to switch comparison mode.');
			}
		}
	);
	context.subscriptions.push(switchComparisonModeCommand);

	console.log('Gitbbon Manager extension activated!');
}

/**
 * Extension deactivation
 */
export function deactivate(): void {
	console.log('Gitbbon Manager extension deactivated');
}
